#!/bin/bash

echo "=== SCRIPT PARA REFRESCAR EL ADDON EN ODOO ==="
echo ""
echo "Este script te ayudará a actualizar el addon correctamente en Odoo."
echo ""
echo "PASOS A SEGUIR:"
echo ""
echo "1. 🔄 ACTUALIZAR EL ADDON:"
echo "   - Ve a Aplicaciones > Aplicaciones"
echo "   - Busca 'Website Category Sync'"
echo "   - Haz clic en 'Actualizar' (no 'Desinstalar')"
echo ""
echo "2. 🗂️ LIMPIAR CACHE (si sigue fallando):"
echo "   - Reinicia el servidor Odoo:"
echo "     sudo systemctl restart odoo"
echo "   - O desde la línea de comandos de Odoo:"
echo "     ./odoo-bin --update=website_category_sync -d tu_base_de_datos"
echo ""
echo "3. ✅ VERIFICAR LA INSTALACIÓN:"
echo "   - Ve a Inventario > Configuración > Productos"
echo "   - Busca el menú 'Establecer Sin Seguimiento Global'"
echo "   - El botón debería funcionar sin errores sobre 'detailed_type'"
echo ""
echo "4. 🧪 PROBAR EL WIZARD:"
echo "   - Ejecuta el wizard"
echo "   - Ve a cualquier producto"
echo "   - Verifica que el checkbox 'Rastrear inventario' sea visible"
echo "   - Verifica que esté configurado en 'Sin seguimiento'"
echo ""
echo "=== VERSIÓN ACTUAL DEL ADDON ==="
grep "version" __manifest__.py
echo ""
echo "=== SI CONTINÚA EL ERROR ==="
echo "1. Verifica que estés usando la versión correcta del addon"
echo "2. Asegúrate de que Odoo se reinició después de la actualización"
echo "3. Revisa los logs de Odoo para más detalles"
echo ""
echo "¡El addon está listo y no contiene referencias a 'detailed_type'!"
